made Intel's icc happy:
since variables c1 & c2 are only used in
"#ifndef NDEBUG"-guarded code,
make sure that also their declaration is
"#ifndef NDEBUG"-guarded; otherwise icc
complains:
 icc -no-gcc -DHAVE_CONFIG_H -I. -I/export/scratch0/monet/monet.ntv.64.64.d.27373/pathfinder/compiler/algebra/opt -I../../.. -I/export/scratch0/monet/monet.ntv.64.64.d.27373/pathfinder/compiler/algebra/opt -I../../include -I/export/scratch0/monet/monet.ntv.64.64.d.27373/pathfinder/compiler/algebra/opt/../../include -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB/common -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB/gdk -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB/monet -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB/plain -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB/contrib -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB/mapi -I/export/scratch0/monet/monet.ntv.64.64.d.27373/MonetDB/.ntv.64.64.d-Fedora4/include/MonetDB/C -DLIBOPT -we140 -wd1418 -c99 -Wall -w2 -mp1 -O3 -restrict -unroll -tpp7 -axWP -we266 -Werror -wd1418,1419,279,310,981,810,444,193,111,177,171,181,764,269,108,188,1357,102,70,1572 -c /export/scratch0/monet/monet.ntv.64.64.d.27373/pathfinder/compiler/algebra/opt/opt_const.c  -KPIC -DPIC -o .libs/libopt_la-opt_const.o
/export/scratch0/monet/monet.ntv.64.64.d.27373/pathfinder/compiler/algebra/opt/opt_const.c(390): error #185: dynamic initialization in unreachable code
              bool all_const = true;
                   ^

/export/scratch0/monet/monet.ntv.64.64.d.27373/pathfinder/compiler/algebra/opt/opt_const.c(477): error #185: dynamic initialization in unreachable code
                  PFalg_att_t *atts = PFmalloc (p->schema.count *
                               ^

compilation aborted for /export/scratch0/monet/monet.ntv.64.64.d.27373/pathfinder/compiler/algebra/opt/opt_const.c (code 2)
make[8]: *** [libopt_la-opt_const.lo] Error 1

see also
http://monetdb.cwi.nl/Development/TestWeb/Current/pathfinder/
and
http://monetdb.cwi.nl/testing/projects/monetdb/Current/pathfinder/.ntv.64.64.d-Fedora4/conf.bash.out