Work around clang bug on Ubuntu 24.04 LTS. The problem manifests itself when using __builtin_mul_overflow which causes an undefined reference to __muloti4.