Use YYERROR_VERBOSE to increase the quality of error messages:
monetdb-> select * from (select tables join tables);
Error: syntax error, unexpected JOIN, expecting INTERSECT or EXCEPT or
UNION in: "select * from (select tables join"

instead of:

Error: syntax error at token (257)

remove rule that generate reduce/reduce conflict, try to help the parser
in generating a useful error message by rearranging the rules a bit and
lowercase all error messages in order to be consistant.