mal_readline: also include prototypes without libreadline
Since we always have the functions, regardless of HAVE_LIBREADLINE, gcc
will spit out an error like:
  error: no previous prototype for 'getConsoleInput'
hence don't include the own header file conditionally