strcasestr: make definition match GNU's
Define our fallback strcasestr with const arguments since we don't
change them, and hence can.  It is necessary to allow compilation on
platforms that lack strcasestr, such as Solaris:

pcre.c:166:4: error: passing argument 1 of 'strcasestr' discards 'const'
qualifier from pointer target type [-Werror]