fixing compilation error
.../pathfinder/compiler/mil/milprint.c:433: error: initialized field overwritten
.../pathfinder/compiler/mil/milprint.c:433: error: (near initialization for ‘ID[111]’)

there is no need to initialize the same field twice with the same value