Fix ICC compilation error
monetdb-buildbot/x86_64-fedora12icc/build/sources/five/src/mal/mal_interpreter.mx(364): error #593: variable "keepAlive" was set but never used