rel_create_index(): use idx_type instead of int
icc complained about
sql/server/rel_schema.c(1527): error #188: enumerated type mixed with another type
  i = mvc_create_idx(sql, nt, iname, itype);
                                     ^
hence, we change argument itype of function rel_create_index()
(the only place where mvc_create_idx() is called)
from int to idx_type,
and cast argument l->h->next->data.i_val to idx_type
when calling rel_create_index() in rel_schemas()

I hope this is correct and as intended;
Niels should double-check ...