make sure that "pf_config.h" is FIRST include file in EACH .c file (either directly or via "pathfinder.h").
This solved the following error, when compiling both
the main branch (HEAD) and the "Core2MIL_Summer2004" branch
with the main branch of MonetDB (4.3.17):
========
gcc -DHAVE_CONFIG_H -I. -I/ufs/manegold/Monet/4.3/pathfinder/compiler/daemon -I../.. -I/ufs/manegold/Monet/4.3/pathfinder/compiler/daemon -I../include -I/ufs/manegold/Monet/4.3/pathfinder/compiler/daemon/../include -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/common -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/gdk -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/monet -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/plain -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/contrib -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/mapi -ansi -std=c99 -Wall -W -g -DHWCOUNTERS -DHW_Linux -DHW_i686 -Werror-implicit-function-declaration -Werror -Wno-format -Wno-unused-function -Wno-unused-label -c /ufs/manegold/Monet/4.3/pathfinder/compiler/daemon/daemon.c  -fPIC -DPIC -o daemon.lo
/ufs/manegold/Monet/4.3/pathfinder/compiler/daemon/daemon.c: In function `daemonize':
/ufs/manegold/Monet/4.3/pathfinder/compiler/daemon/daemon.c:120: implicit declaration of function `fileno'
make[3]: *** [daemon.lo] Error 1
========

However, one problem still remains when compiling
the "Core2MIL_Summer2004" branch
with the main branch of MonetDB (4.3.17):
========
gcc -DHAVE_CONFIG_H -I. -I/ufs/manegold/Monet/4.3.16/pathfinder/compiler/semantics -I../.. -I/ufs/manegold/Monet/4.3.16/pathfinder/compiler/semantics -I../include -I/ufs/manegold/Monet/4.3.16/pathfinder/compiler/semantics/../include -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/common -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/gdk -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/monet -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/plain -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/contrib -I/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/include/MonetDB/mapi -ansi -std=c99 -Wall -W -g -DHWCOUNTERS -DHW_Linux -DHW_i686 -c typecheck.c  -fPIC -DPIC -o typecheck.lo
tmp.mt: In function `mtAction':
tmp.mt:531: invalid operands to binary !=
tmp.mt:554: invalid operands to binary !=
make[4]: *** [typecheck.lo] Error 1
========

I was not able to solve this, yet...